name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the build on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: anaghakumbale/scholar3:latest  # Change this to your Docker image name
      run: |
        docker buildx create --use
        docker buildx inspect default --bootstrap
        docker buildx build --push --tag $IMAGE_NAME .

